### ISSUE TITLE
NOOB Question - Starting the script

### ISSUE THREAD

**Issue by xbmcnut** [sumnerboy12/mqtt-gpio-monitor#12]
Hi. Thanks for creating this. I'm going to use it with Home Assistant. Dumb question though. How do I start the script? Don't know where these things get installed as I'm a hardware guy and searching for pifacedigitalio or mqtt-gpio-monitor.ini with WinSCP did not yield any results.

**Comment by sumnerboy12** [comment]
Up to you really, I use `supervisor` to manage these sorts of little scripts. Google it, there are plenty of tutorials and guides on how to use that to run simple python scripts like this.

**Comment by xbmcnut** [comment]
Thanks for the prompt reply Ben. Will do, but where is the .ini and .py file located on install?

**Comment by sumnerboy12** [comment]
Whereever you like - your `supervisor` config script will point to the location. Something like this;

- `sudo apt-get install supervisor`

- Edit `/etc/supervisor/conf.d/mqtt-gpio-monitor.conf`
```
[program:<program-name>]
directory = <program-directory>
command = <program-command>
user = <program-user>
```

- `sudo supervisorctl update`
- `sudo supervisorctl reload`

**Comment by xbmcnut** [comment]
Thanks again Ben. Sorry to be a pain in the arts, but I'm a bit confused. I thought running `sudo apt-get install python-pifacedigitalio` would install mqtt-gpio-monitor.py and mqtt-gpio-monitor.ini.example (to be edited) so I'm looking around for those files. Am I missing something?

**Comment by sumnerboy12** [comment]
Nope - there is no installation package for this script - you have to `git clone` it locally and run yourself.

**Comment by xbmcnut** [comment]
Ah, OK, got it. Still getting my head around Linux.
