### ISSUE TITLE
Set pull-up or pull-down resistor in config

### ISSUE THREAD

**Issue by Rtaxerxes** [sumnerboy12/mqtt-gpio-monitor#14]
I'm not a programmer, but I've looked through the code and can't see a way to set the pull up resistors. I see in line 272: GPIO.setup(pin, GPIO.IN, pull_up_down=GPIO.PUD_UP), but I don't see a way to set it.

I've done it manually on the command line by running 'gpio -g mode 17 up'.

**Comment by sumnerboy12** [comment]
You are correct, there is no way to set this via configuration. I would welcome a pull request to add this if you are interested.

**Comment by Rtaxerxes** [comment]
I can try...

**Comment by filcole** [comment]
I've made this change in my branch.  I can submit a pull request if wanted.  https://github.com/filcole/mqtt-gpio-monitor.  There's quite a few other tweaks in there too.

**Comment by sumnerboy12** [comment]
Yes please.

**Comment by sumnerboy12** [comment]
Resolved via https://github.com/sumnerboy12/mqtt-gpio-monitor/pull/15.
