### ISSUE TITLE
log file

### ISSUE THREAD

**Issue by timtimsson** [sumnerboy12/mqtt-gpio-monitor#17]
Hello,
is it possible to change the default log-file target?
Thanks!

**Comment by sumnerboy12** [comment]
Yes, by specifying the `LOGFILE` system environment variable;

```
LOGFILE = os.getenv('LOGFILE', APPNAME + '.log')
```

**Comment by timtimsson** [comment]
Hi,
if i would change the target to /var/log/mqtt-gpio-monitor - is this the right syntax:
? LOGFILE = os.getenv('/var/log/mqtt-gpio-monitor ', APPNAME + '.log') ?

**Comment by sumnerboy12** [comment]
You need tp set the environment variable in your session. Google is your friend, there are plenty of tutorials about how to do this. You don't need to touch the source code. Although you can if you want of course.
