### ISSUE TITLE
problem with the new version...

### ISSUE THREAD

**Issue by timtimsson** [sumnerboy12/mqtt-gpio-monitor#18]
Hi,
i use your old version and this works very well :)
Now i copy the new version and i have the following mistake:

`sudo ./mqtt-gpio-monitor.py
Traceback (most recent call last):
  File "./mqtt-gpio-monitor.py", line 14, in <module>
    import paho.mqtt.client as mqtt
ImportError: No module named 'paho'`

python --version
Python 2.7.9

What can i do?

**Comment by timtimsson** [comment]
shame... -> i don't see **python3**

**Comment by thermike2** [comment]
I have a similar problem have you solved yours?
