### ISSUE TITLE
How many GPIO

### ISSUE THREAD

**Issue by arlowf** [sumnerboy12/mqtt-gpio-monitor#19]
Assuming I have a very powerful embedded SOM running Linux (Artik 710) with 8 cores running fedora with python: how many gpio could this monitor and how much "traffic" could it handle? Could it monitor 100 gpio/pins and 10 messages per second with 10 onboard subscribers? Just trying to understand if I can use this for managing onboard interprocess communication.

**Comment by sumnerboy12** [comment]
I have no idea sorry - never tried it on that sort of system.
