### ISSUE TITLE
MONITOR_OUT_INVERT will always invert

### ISSUE THREAD

**Issue by m-menon** [sumnerboy12/mqtt-gpio-monitor#23]
Thanks for the nice script. Works really well and very well written. One little thing I wanted to point out was ( probably a typo I guess )

[config.get](https://github.com/sumnerboy12/mqtt-gpio-monitor/blob/master/mqtt-gpio-monitor.py#L50)

should be `config.getboolean(...` instead of `config.get(...`

Cheers,
M.M

**Comment by sumnerboy12** [comment]
@filcole could you have a look at this? I think it might have been introduced by your change earlier in 2017.

**Comment by sumnerboy12** [comment]
Thanks for reporting this @m-menon - should be fixed now.

**Comment by m-menon** [comment]
Cool. Thanks :+1:
