### ISSUE TITLE
Get Status of out pins

### ISSUE THREAD

**Issue by bgewehr** [sumnerboy12/mqtt-gpio-monitor#5]
When a pin is in Out mode it does not show the status to mqtt when changed from another source, let's say local script action or reboot.

Do you have a solution for this like polling the out pins and generating out messages on the bus?

**Comment by bgewehr** [comment]
sudo gpio read 17 for example is able to read if it is 0 or 1 so polling could be a chance, right? On the other hand the script would have to remember all states and poll to proof if a difference to the remembered has occurred. Hm...

**Comment by sumnerboy12** [comment]
This would require a second polling loop to monitor the state of the output pins. I am not sure how simple this would be to implement. The general idea of this script was to allow a very simple way to monitor some input pins, and control some output pins. Where the output pins are controlled _only_ by the script. I am a little wary of over-complicating things as currently the script works very well for me ;).
