### ISSUE TITLE
Autostart mqtt

### ISSUE THREAD

**Issue by w4rn** [sumnerboy12/mqtt-gpio-monitor#9]
Hello,
is there any way to start the mqtt monitor when rpi boot?

ty

**Comment by sumnerboy12** [comment]
I use the supervisor daemon to do this. It also has a web server so you can
remotely start and stop the service.

**Comment by bgewehr** [comment]
I used init scripts with success to do that.

Look at http://github.com/bgewehr/gartenwasser in the etc/init.d folder for examples.
